### ISSUE TITLE
Selective trigger

### ISSUE THREAD

**Issue by Iain-S** [Iain-S/AdventOfAction#11]
Some solutions are going to be expensive so it'd be good to only run, for example, the ones newly submitted by a PR.

**Comment by Iain-S** [comment]
One option would be to use one of these three solutions suggested by ChatGPT:

Yes! Within a GitHub Action, you can determine whether a file was changed in a pull request (PR) using the `github` context or by using `git` commands. Here are a few approaches:

---

### **1. Use `actions/checkout` and `git diff`**
You can compare the PR’s changes against the base branch.

```yaml
steps:
  - name: Checkout Code
    uses: actions/checkout@v4
    with:
      fetch-depth: 0  # Ensures full git history is available

  - name: Get Changed Files
    run: |
      CHANGED_FILES=$(git diff --name-only origin/${{ github.event.pull_request.base.ref }})
      echo "Changed files:"
      echo "$CHANGED_FILES"

      # Check if a specific file was changed
      if echo "$CHANGED_FILES" | grep -q "path/to/myfile.txt"; then
        echo "myfile.txt was changed!"
      fi
```

---

### **2. Use `dorny/paths-filter` Action**
This GitHub Action makes it easier to check for changed files.

```yaml
- name: Check for Changes
  uses: dorny/paths-filter@v3
  id: changes
  with:
    filters: |
      myfile:
        - 'path/to/myfile.txt'
      src:
        - 'src/**'

- name: Run only if myfile.txt changed
  if: steps.changes.outputs.myfile == 'true'
  run: echo "myfile.txt was modified!"
```

---

### **3. Use `github.event` Directly**
For PR events, GitHub provides a list of changed files via the REST API:

```yaml
- name: Get Changed Files via API
  run: |
    CHANGED_FILES=$(gh pr view ${{ github.event.pull_request.number }} --json files -q '.files[].path')
    echo "Changed files: $CHANGED_FILES"
  env:
    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

This requires `gh` (GitHub CLI), which is preinstalled on GitHub-hosted runners.

---

### **Which One to Use?**
- **For simple file checks:** `git diff` is lightweight.
- **For structured filtering:** `dorny/paths-filter` is best.
- **For API-based checking:** `gh pr view` works well.

Would you like to run specific benchmarks based on changed files in your workflow?
